apiVersion: v1
kind: BuildConfig
metadata:
  name: dwakeman.test-java-spring
  labels:
    app: test-java-spring
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/dwakeman/test-java-spring.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dw-spring-dev
        - name: BRANCH
          value: master
